### ISSUE TITLE
Why many add-on interface translations do not appear in the SVN repository

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/mrconfig#45]
Hi all, I've noticed that a lot of add-ons have been updated recently, but I don't see the interface translation po files for these add-ons in the SVN repository, what am I missing?

**Comment by CyrilleB79** [comment]
Hi
There may be many reasons. I can see two of them:
* add-on are not integrated in translation framework, e.g. because the author did not make the request
* you did not enable them in the settings file of your language

You need to give more details if you want your question to be answered. List of the add-ons that are not updated and language for which you translate.

Thanks.

**Comment by cary-rowen** [comment]
Hello @CyrilleB79

wordNav, checkGestures, and Win Wizard did not appear in zh_cn/addons.

Thanks.

**Comment by CyrilleB79** [comment]
I guess they are not part of the translation framework.
If you want them translated, you should ask the author to request their registration in the translation system.

**Comment by feerrenrut** [comment]
You can check for inclusion of addons by looking at this file: https://github.com/nvaccess/mrconfig/blob/master/automatic.crontab

**Comment by cary-rowen** [comment]
I thank, Some of the developers of these add-ons may not know how to register their translations.
Thank you both.
I close this issue first

**Comment by CyrilleB79** [comment]
Developers can ask guidance on the add-on mailing list if needed.

There has been a time when I was unsure if everything was working well in the translation framework and NVAccess (Reef) probably had less time to answer and fix issues due to NVDA 2021.1 release. Now, all the steps are completed successfully for Outlook Extended. And Reef answers more regularily to the requests regarding translation.
I will try to answer such request on the list if any in the future and help identifying any blocking point if any.
