### ISSUE TITLE
[Register add-on in translation system]: 

### ISSUE THREAD

**Issue by mohammad-suliman** [nvaccess/mrconfig#57]
### Add-on name

Zoom Accessibility Enhancements

### Add-on maintainer

@mohammad-suliman

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by nvdaes** [comment]
@mohammad-suliman , the add-on name shouldn't contain spaces (it's not the summary or display name but the internal name or identifier). Also, stable branch means stable branch in the nvdaaddons repo and it'is not present since your add-on is not forked yet. You need to wait to create the issue until the add-on has been forked, or the member of the nvdaaddons organization can create the issue for you after forking the add-on and send you an invitation so you can merge your work in the stable branch of the fork for translations. When you create, edit or reopen an issue to request add-on registration, GitHub Actions checks if the stable branch is present, and this is the reason for which you have to wait.
In addition, I'm not sure if your repository needs to be named exactly as your add-on. Your repository contains a dash and, according to old add-on guidelines, add-ons cannot contain dashes in names since they aren't supported by the system. I don't know if this is different now.
Your add-on doesn't contain dashes in its name, but the repo does. Hope this is not a problem. I'd wait for a clarification about this or, if this is not an inconvenience for you, you may prefer to rename your repo like zoomEnhancements. Underscores were always supported, but not dashes.

**Comment by feerrenrut** [comment]
The actual addon repo seems to be: https://github.com/mohammad-suliman/zoom-enhancements

The addonName / id from buildVars.py is: "zoomEnhancements"

These will work fine.
Next steps:
- @mohammad-suliman please create a branch called 'stable' on the repository.
- Then, @nvdaes please fork and give permissions to @nvaccessAuto

**Comment by nvdaes** [comment]
I'll fork the repo when Mohammad creates the stable branch and try to
grant write permission to nvaccessauto.

2021-08-16 13:08 GMT+02:00, Reef Turner ***@***.***>:

**Comment by mohammad-suliman** [comment]
Thanks for the quick responses! Just to be sure, I need to create the
stable branch in my repo, correct?

**Comment by nvdaes** [comment]
Yes please, create the stable branch in your repo and then I'll fork it.

2021-08-16 14:45 GMT+02:00, mohammad-suliman ***@***.***>:

**Comment by mohammad-suliman** [comment]
Thanks Noelia! The branch has been created.

**Comment by nvdaes** [comment]
@mohammad-suliman, I've sent you an invitation to the nvdaaddons fork of your repo so you can maintain it (write access).
@feerrenrut , now nvaccessauto is an owner of nvdaaddons organization, so the account has full permissions for all repos. You can register this add-on in the translations system. I think that, if you want GitHub Actions to check this like done in other issues, this has to be edited. Another possibility would be to add the workflow_dispatch event to the .yaml file for manual triggers.

**Comment by feerrenrut** [comment]
For reference, the repository name should match the addon name, with some manual effort I can work around it in this case. No action required from @mohammad-suliman or @nvdaes 

zoomEnhancements is now available for translation.
